<!--#if (IncludeWebApi || IncludeMinimalApi) -->
<Project Sdk="Microsoft.NET.Sdk.Web">
<!--#elseif (IncludeWorker) -->
<Project Sdk="Microsoft.NET.Sdk.Worker">
<!--#else -->
<Project Sdk="Microsoft.NET.Sdk">
<!--#endif -->

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-minimum</AnalysisLevel>
<!--#if (IncludeConsole) -->
    <OutputType>Exe</OutputType>
<!--#endif -->
  </PropertyGroup>

<!--#if (IncludeWebApi || IncludeMinimalApi) -->
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.*" />
  </ItemGroup>
<!--#endif -->

<!--#if (IncludeConsole || IncludeWorker) -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.*" />
  </ItemGroup>
<!--#endif -->

<!--#if (IncludeSwaggerUI && IncludeNet8) -->
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="__SwashbuckleVersion__" />
  </ItemGroup>
<!--#endif -->
<!--#if (IncludeSwaggerUI && !IncludeNet8) -->
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="__SwashbuckleVersion__" />
  </ItemGroup>
<!--#endif -->
<!--#if (IncludeSerilog) -->
  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="10.*" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.*" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.*" />
  </ItemGroup>
<!--#endif -->
<!--#if (IncludeNLog && IncludeWebProject) -->
  <ItemGroup>
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.*" />
  </ItemGroup>
<!--#elif (IncludeNLog && !IncludeWebProject) -->
  <ItemGroup>
    <PackageReference Include="NLog.Extensions.Hosting" Version="6.*" />
  </ItemGroup>
<!--#endif -->
<!--#if (IncludeScalar) -->
  <ItemGroup>
    <PackageReference Include="Scalar.AspNetCore" Version="2.*" />
  </ItemGroup>
<!--#endif -->
<!--#if (IncludeRedoc && IncludeNet8) -->
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore.ReDoc" Version="__SwashbuckleVersion__" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="__SwashbuckleVersion__" />
  </ItemGroup>
<!--#endif -->
<!--#if (IncludeRedoc && !IncludeNet8) -->
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore.ReDoc" Version="__SwashbuckleVersion__" />
  </ItemGroup>
<!--#endif -->
<!--#if (IncludeHangfire && IncludeWebProject) -->
  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.*" />
  </ItemGroup>
<!--#endif -->

  <ItemGroup>
    <ProjectReference Include="../Company.ProjectName.Infrastructure/Company.ProjectName.Infrastructure.csproj" />
    <ProjectReference Include="../Company.ProjectName.Application/Company.ProjectName.Application.csproj" />
  </ItemGroup>

</Project>
