<!--#if (IncludeWebApi || IncludeMinimalApi) -->
<Project Sdk="Microsoft.NET.Sdk.Web">
<!--#elseif (IncludeWorker) -->
<Project Sdk="Microsoft.NET.Sdk.Worker">
<!--#else -->
<Project Sdk="Microsoft.NET.Sdk">
<!--#endif -->

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-minimum</AnalysisLevel>
<!--#if (IncludeConsole) -->
    <OutputType>Exe</OutputType>
<!--#endif -->
  </PropertyGroup>

<!--#if (IncludeWebApi || IncludeMinimalApi) -->
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.*" />
  </ItemGroup>
<!--#endif -->

<!--#if (IncludeConsole || IncludeWorker) -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.*" />
  </ItemGroup>
<!--#endif -->

<!--#if (IncludeEfCore) -->
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="__EfCoreVersion__" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="__EfCoreVersion__" />
<!--#if (IncludePostgreSql) -->
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="__NpgsqlEfVersion__" />
<!--#elif (IncludeSqlServer) -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="__EfCoreVersion__" />
<!--#elif (IncludeMySql) -->
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="__PomeloVersion__" />
<!--#elif (IncludeSqlite) -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="__EfCoreVersion__" />
<!--#endif -->
  </ItemGroup>
<!--#endif -->
<!--#if (IncludeDapper) -->
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.*" />
<!--#if (IncludePostgreSql) -->
    <PackageReference Include="Npgsql" Version="9.*" />
<!--#elif (IncludeSqlServer) -->
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.*" />
<!--#elif (IncludeMySql) -->
    <PackageReference Include="MySqlConnector" Version="2.*" />
<!--#elif (IncludeSqlite) -->
    <PackageReference Include="Microsoft.Data.Sqlite" Version="__EfCoreVersion__" />
<!--#endif -->
  </ItemGroup>
<!--#endif -->
<!--#if (IncludeJwt || IncludeKeycloak) -->
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="__EfCoreVersion__" />
  </ItemGroup>
<!--#endif -->
<!--#if (IncludeAspNetIdentity) -->
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="__EfCoreVersion__" />
  </ItemGroup>
<!--#endif -->
<!--#if (IncludeSwaggerUI && IncludeNet8) -->
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="__SwashbuckleVersion__" />
  </ItemGroup>
<!--#endif -->
<!--#if (IncludeSwaggerUI && !IncludeNet8) -->
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="__SwashbuckleVersion__" />
  </ItemGroup>
<!--#endif -->

</Project>
